[options]
  colorscheme = "dracula"
  colorscheme_bg = "dark"
  enable_guicolors = true
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  autocomplete_method = "ycm"
  filemanager = "nerdtree"
  filetree_direction = "left"

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "git"

[[layers]]
  name = 'autocomplete'

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "lang#php" 

[[layers]]
  name = "lang#javascript"

[[layers]]
  name = "lang#python"
  format-on-save = 1

[[layers]]
  name = "lang#java"

[[layers]]
  name = "VersionControl"

[[layers]]
  name = "core#statusline"

[[layers]]
    name = "denite"

[[layers]]
  name = "fzf"

[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
  name = "lang#asciidoc"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#plantuml"

[[layers]]
  name = "lang#graphql"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#typescript"

[[layers]]
  name = "checkers"
  show_cursor_error = false

[[layers]]
  name = "lang#vue"

[[layers]]
  name = "tmux"

[[layers]]
  name = "unite"

[[layers]]
  name = "tools"

[[layers]]
  name = "tools#zeal"

[[custom_plugins]]
  name = 'cespare/vim-toml'
  merged = 0

[[custom_plugins]]
  name = "dracula/vim"