[options]
  colorscheme = "dracula"
  colorscheme_bg = "dark"
  enable_guicolors = true
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  autocomplete_method = "ycm"
  filemanager = "nerdtree"
  filetree_direction = "left"
  enable_statusline_mode = true

[[layers]]
  name = "format"
  format_on_save = true

[[layers]]
  name = "colorscheme"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = 'autocomplete'

[[layers]]
  name = 'ui'
  enable_scrollbar = true

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "checkers"
  enable_neomake = false
  enable_ale = true

[[layers]]
  name = "leaderf"

[[layers]]
  name = "core#statusline"

[[layers]]
  name = "VersionControl"

[[layers]]
    name = "denite"

[[layers]]
  name = "fzf"

[[layers]]
  name = "gtags"
  gtagslabel = "pygments"

[[layers]]
  name = "tmux"

[[layers]]
  name = "tools"

[[layers]]
  name = "lang#asciidoc"

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#markdown"

[[layers]]
  name = "lang#plantuml"

[[layers]]
  name = "lang#graphql"

[[layers]]
  name = "lang#rust"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#typescript"


[[layers]]
  name = "lang#vue"

[[layers]]
  name = "tools#zeal"

[[custom_plugins]]
  name = 'cespare/vim-toml'
  merged = 0

[[custom_plugins]]
  name = "dracula/vim"

[[custom_plugins]]
  name = "nathanaelkane/vim-indent-guides"
  merged = 0
