source ~/.local-antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle aws
antigen bundle docker
antigen bundle vagrant
antigen bundle pip
antigen bundle fzf
antigen bundle lein
antigen bundle nvm
antigen bundle virtualenv
antigen bundle wfxr/forgit 
antigen bundle colored-man-pages
antigen bundle desyncr/auto-ls
antigen bundle lukechilds/zsh-nvm
antigen bundle command-not-found
antigen bundle gko/ssh-connect
antigen bundle chrissicool/zsh-256color
antigen bundle djui/alias-tips
antigen bundle webyneter/docker-aliases
antigen bundle zsh-users/zsh-syntax-highlighting
antigen bundle zsh-users/zsh-autosuggestions
antigen bundle zsh-users/zsh-completions
antigen bundle zsh-users/zsh-history-substring-search

antigen theme denysdovhan/spaceship-prompt

antigen apply

if test -f "$HOME/.sdkman/bin/sdkman-init.sh"; then
    . $HOME/.sdkman/bin/sdkman-init.sh
fi

alias du="ncdu --color dark"
alias ls='exa'
alias cat='bat'
alias df='duf'
alias k='kubectl'
alias kn='kubens'
alias kx='kubectx'
