source ~/.zplug/init.zsh

zplug "zsh-users/zsh-syntax-highlighting"
zplug "zsh-users/zsh-autosuggestions"
zplug "zsh-users/zsh-history-substring-search"
zplug "zsh-users/zsh-completions"
zplug "joshskidmore/zsh-fzf-history-search"
zplug "softmoth/zsh-vim-mode"
zplug "woefe/git-prompt.zsh"
zplug "Aloxaf/fzf-tab"
zplug "desyncr/auto-ls"
zplug "supercrabtree/k"
zplug "lukechilds/zsh-nvm"
zplug "chitoku-k/fzf-zsh-completions"
zplug "plugins/kubectl", from:oh-my-zsh, defer:2
zplug "bonnefoa/kubectl-fzf", defer:3

zplug "dracula/zsh", as:theme

if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    else
        echo
    fi
fi
zplug load

HISTFILE=~/.zsh_history
HISTSIZE=1000000
SAVEHIST=1000000

. ~/.sdkman/bin/sdkman-init.sh

alias du="ncdu --color dark"
alias ls='exa --icons --git'
alias ll='exa -l --icons --git'
alias l='ll'
alias cat='bat'
alias df='duf'
alias k='kubectl'
alias kn='kubens'
alias kx='kubectx'
