---
- name: Alacritty | Check if the binary is present
  stat:
    path: /usr/bin/alacritty
  register: alacritty_bin_path

- name: Alacritty | Check if repository is configured
  stat:
    path: /etc/apt/sources.list.d/alacritty.list
  register: alacritty_repository_exists

- name: Alacritty | Ensure that exists a version in this release
  uri:
    url: "http://ppa.launchpad.net/mmstick76/alacritty/ubuntu/dists/{{ ansible_distribution_release }}/"
    method: HEAD
  ignore_errors: yes
  register: alacritty_repository_release_exists

- name: Alacritty | Install Alacritty
  block:
  - name: Allacritty | Add package repository
    apt_repository:
      repo: "ppa:mmstick76/alacritty"
      filename: alacritty
      update_cache: yes
      state: present
    become: true
  - name: Allacritty | Install the package
    package:
      name: alacritty
      state: present
      force_apt_get: true
    become: true
  when: alacritty_bin_path.stat.exists == false and alacritty_repository_release_exists.status == 200