---
- name: Android Studio | Check if is present
  stat:
    path: /opt/android-studio/bin/studio.sh
  register: androidstudio_bin_path

- name: Android Studio | Ensure that exists a version in this release
  uri:
    url: "http://ppa.launchpad.net/maarten-fonville/android-studio/ubuntu/dists/{{ ansible_distribution_release }}/"
    method: HEAD
  ignore_errors: yes
  retries: 3
  until: androidstudio_repo.status == 200
  register: androidstudio_repo

- name: Android Studio | Add package repository
  when: androidstudio_repo.status == 200
  apt_repository:
    repo: "ppa:maarten-fonville/android-studio"
    filename: androidstudio
    update_cache: yes
    state: present
  become: true
  retries: 3

- name: Android Studio | Install the package
  when: androidstudio_bin_path.stat.exists == false and androidstudio_repo.status == 200
  package:
    name: android-studio
    state: present
    force_apt_get: true
  become: true
  retries: 3
