- name: Broot | Check if is present
  stat:
    path: /usr/local/bin/broot
  register: broot_bin_path

- name: Broot | Check avaliable version
  command: /usr/local/bin/broot --version
  register: broot_bin_version
  ignore_errors: true

- name: Broot | Register local version
  set_fact:
    broot_local_version: "{{ broot_bin_version.stdout | regex_findall('(\\d+\\.\\d+.\\d+)') | first }}"
  when: broot_bin_version.rc == 0

- name: Broot | Register local version
  set_fact:
    broot_local_version: ""
  when: broot_bin_version.rc != 0

- name: Broot | Recover all releases
  uri:
    url: https://api.github.com/repos/canop/broot/releases
    return_content: true
    body_format: json
  retries: 3
  register: broot_releases_response

- name: Broot | Get latest version URL
  set_fact:
    broot_download_url: "{{ broot_releases_response.content | from_json | first | json_query('assets[?starts_with(name, `broot`)].browser_download_url') | first }}"

- name: Broot | Set latest remote version
  set_fact:
    broot_remote_version: "{{ broot_download_url | regex_findall('(\\d+\\.\\d+.\\d+)') | first }}"

- name: Broot | get the zip file
  when: broot_local_version != broot_remote_version or broot_bin_path.stat.exists == false
  get_url:
    url: "{{ broot_download_url }}"
    dest: "/tmp"

- name: Broot | Install or Upgrade
  shell: "unzip -j -o /tmp/{{ broot_download_url | basename }} build/x86_64-linux/broot -d /usr/local/bin"
  args:
    warn: false
  become: true
  when: broot_local_version != broot_remote_version or broot_bin_path.stat.exists == false
