---
- name: Codecs | Ensures that all packages are present
  package:
    name:
      - libavcodec-extra
      - ffmpeg
      - easytag
      - id3tool
      - lame
      - libmad0
      - faac
      - faad
      - ffmpeg2theora
      - flac
      - icedax
      - id3v2
      - lame
      - libflac++6v5
      - libjpeg-progs
      - mjpegtools
      - mpeg2dec
      - mpeg3-utils
      - mpegdemux
      - mpg123
      - mpg321
      - regionset
      - sox
      - uudeview
      - vorbis-tools
      - x264
      - audacious
      - ubuntu-restricted-extras
    state: latest
    force_apt_get: yes
  retries: 3
  become: true
