---
- name: Container | Include related tasks
  include_tasks: "{{ container_tasks }}.yml"
  loop:
    - docker
    - podman
    - buildah
    - dry
    - dive
    - kubernetes
    - docker-compose
  loop_control:
    loop_var: container_tasks
