---
- name: Dive | Check if is present
  stat:
    path: /usr/local/bin/dive
  register: dive_exists

- name: Dive | Install or Upgrade
  block:
    - name: Dive | Recover all releases
      uri:
        url: https://api.github.com/repos/wagoodman/dive/releases
        return_content: true
        body_format: json
        headers:
          Authorization: "token {{ GH_TOKEN }}"
      retries: 3
      register: dive_releases_response

    - name: Dive | Get deb latest version URL
      set_fact:
        dive_deb_download_url: "{{ dive_releases_response.content | from_json | first | json_query('assets[?ends_with(name, `_amd64.deb`)].browser_download_url') | first }}"

    - name: Dive | Set latest avaliable version
      set_fact:
        dive_latest_version: "{{ dive_deb_download_url | regex_findall('(\\d+\\.\\d+\\.\\d+)') | first }}"

    - name: Dive | Set local version
      set_fact:
        dive_local_version: "{{ ansible_facts.packages['dive'][0].version }}"
      ignore_errors: true

    - name: Dive | Install deb file
      apt:
        deb: "{{ dive_deb_download_url }}"
        force_apt_get: yes
      become: true
      retries: 3
      when: (dive_local_version is defined and dive_local_version != dive_latest_version) or dive_exists.stat.exists == false
