---
- name: Essential | Install essential packages
  package:
    name:
      - curl
      - wget
      - git
      - git-flow
      - libssl-dev
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - unzip
      - gdebi
      - bash-completion
      - gconf-service
      - gconf-service-backend
      - gconf2-common
      - gconf2
      - libgconf-2-4
    state: latest
    force_apt_get: yes
  become: true
