- name: Etcher | Check if is present
  stat:
    path: /opt/balenaEtcher/balena-etcher-electron
  register: etcher_exists

- name: Etcher | Install or Upgrade
  block:
    - name: Etcher | Install dependencies
      package:
        state: present
        name:
          - libappindicator1
          - libdbusmenu-gtk4
          - libpango1.0-0
          - libpangox-1.0-0
        force_apt_get: true
      become: true
      retries: 3
      when: etcher_exists.stat.exists == false

    - name: Etcher | Recover all releases
      uri:
        url: https://api.github.com/repos/balena-io/etcher/releases
        return_content: true
        body_format: json
        headers:
          Authorization: "token {{ GH_TOKEN }}"
      retries: 3
      register: etcher_releases_response

    - name: Etcher | Get deb latest version URL
      set_fact:
        etcher_deb_download_url: "{{ etcher_releases_response.content | from_json | first | json_query('assets[?ends_with(name, `_amd64.deb`)].browser_download_url') | first }}"

    - name: Etcher | Set latest avaliable version
      set_fact:
        etcher_latest_version: "{{ etcher_deb_download_url | regex_findall('v(\\d+\\.\\d+\\.\\d+)') | first }}"

    - name: Etcher | Set local version
      set_fact:
        etcher_local_version: "{{ ansible_facts.packages['balena-etcher-electron'][0].version }}"
      ignore_errors: true

    - name: Etcher | Install deb file
      apt:
        deb: "{{ etcher_deb_download_url }}"
        force_apt_get: true
      become: true
      retries: 3
      when: (etcher_local_version is defined and etcher_local_version != etcher_latest_version) or etcher_exists.stat.exists == false
