---
- name: Flatpak | Check if repository is configured
  stat:
    path: /etc/apt/sources.list.d/flatpak.list
  register: flatpak_repository_exists

- name: Flatpak | Ensure that exists a version in this release
  uri:
    url: "http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu/dists/{{ ansible_distribution_release }}/"
    method: HEAD
  ignore_errors: yes
  register: flatpack_repository_release_exists

- name: Flatpak | Ensure that the updated repository is present
  block:
    - name: Flatpak | Ensure that the repository is present
      apt_repository:
        repo: ppa:alexlarsson/flatpak
        state: present
        update_cache: yes
        filename: flatpak
      become: true
      ignore_errors: yes
      when: flatpak_repository_exists.stat.exists == false and flatpack_repository_release_exists.status == 200
    - name: Flatpak | Ensures that the package flatpak is installed
      package:
        name:
          - flatpak
          - gnome-software-plugin-flatpak
        state: latest
        force_apt_get: yes
      become: true

    - name: Flatpak | Add the flathub repository remote to the user installation
      flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user
