---
- name: Fonts | Ensure that the user font directory exists
  file:
    state: directory
    path: "{{ ansible_env.HOME }}/.fonts"

- name: Fonts | Include related tasks
  include_tasks: "{{ fonts_tasks }}.yml"
  loop:
    - font-cascadiacode
    - font-firacode
    - font-mscore
  loop_control:
    loop_var: fonts_tasks

- name: Fonts | Ensure that the font cache is updated
  shell: fc-cache -f -v
  become: no
  tags:
    - fonts
