---
- name: Fonts | Check if FiraCode font exists
  stat:
    path: "{{ ansible_env.HOME }}/.fonts/FiraCode-Regular.ttf"
  register: fontsfiracode_exists

- name: Fonts | Downloads and install FiraCode font
  block:
    - name: Fonts | Fira Code | Recover all releases
      uri:
        url: https://api.github.com/repos/tonsky/FiraCode/releases
        return_content: true
        body_format: json
        headers:
          Authorization: "token {{ GH_TOKEN }}"
      retries: 3
      until: firacode_releases_response.status == 200
      register: firacode_releases_response

    - name: Fonts | Fira Code | Get latest version URL
      set_fact:
        firacode_download_url: "{{ firacode_releases_response.content | from_json | first | json_query('assets[?starts_with(name, `Fira_Code`) && ends_with(name, `.zip`)].browser_download_url') | first }}"

    - name: Fonts | Fira Code | Get the zip file
      when: fontsfiracode_exists.stat.exists == false
      get_url:
        url: "{{ firacode_download_url }}"
        dest: "/tmp"
      retries: 3
      register: fontsfiracode_download_file

    - name: Fonts | Fira Code | Install or Upgrade
      when: fontsfiracode_exists.stat.exists == false
      shell: "unzip -j /tmp/{{ firacode_download_url | basename }} ttf/* -d {{ ansible_env.HOME }}/.fonts"
      args:
        warn: false
