---
- name: Indicators | Atareao | Ensure that exists a version in this release
  uri:
    url: "http://ppa.launchpad.net/atareao/atareao/ubuntu/dists/{{ ansible_distribution_release }}/"
    method: HEAD
  ignore_errors: yes
  retries: 3
  register: atareao_atareao_repository_release_exists

- name: Indicators | Atareao  | Check if repository is configured
  stat:
    path: /etc/apt/sources.list.d/atareao_atareao.list
  register: atareao_atareao_repository_exists

- name: Indicators | Atareao | Add package repository
  apt_repository:
    repo: "ppa:atareao/atareao"
    filename: atareao
    update_cache: yes
    state: present
  become: true
  retries: 3
  when: atareao_atareao_repository_release_exists.status == 200 and atareao_atareao_repository_exists.stat.exists == false
  
- name: Indicators | Atareao | Install the package
  package:
    name:
      - calendar-indicator
      - touchpad-indicator
    state: present
    force_apt_get: true
  retries: 3
  become: true