---
- name: Inkscape | Check if is present
  stat:
    path: /usr/bin/inkscape
  register: inkscape_bin_path

- name: Inkscape | Ensure that exists a version in this release
  uri:
    url: "http://ppa.launchpad.net/inkscape.dev/stable/ubuntu/dists/{{ ansible_distribution_release }}/"
    method: HEAD
  ignore_errors: yes
  retries: 3
  register: inkscape_repo

- name: Inkscape | Add package repository
  when: inkscape_repo.status == 200 and inkscape_bin_path.stat.exists == false
  apt_repository:
    repo: "ppa:inkscape.dev/stable"
    filename: inkscape
    update_cache: yes
    state: present
  become: true
  retries: 3

- name: Inkscape | Install the package
  when: inkscape_bin_path.stat.exists == false
  package:
    name: inkscape
    state: present
    force_apt_get: true
  become: true
  retries: 3
