---
- name: Kubernetes | Include related tasks
  include_tasks: "{{ kubernetes_tasks }}.yml"
  loop:
    - kvm
    - kubectl
    - kubectx
    - kubens
    - k9s
    - helm
    - minikube
    - kubeval
    - kind
    - kube-linter
  loop_control:
    loop_var: kubernetes_tasks
