---
- name: Kubernetes | Include related tasks
  include_tasks: "{{ kubernetes_tasks }}.yml"
  loop:
    - kvm
    - kubectl
    - k9s
    - helm
    - minikube
    - kubeval
  loop_control:
    loop_var: kubernetes_tasks
