- name: KVM | Install or Upgrade
  block:
  - name: KVM | Ensures that is installed
    package:
      name:
        - qemu-kvm
        - libvirt-daemon-system
        - libvirt-clients
        - bridge-utils
      state: latest
      force_apt_get: yes
    retries: 3
    become: true