---
- name: Libre Office | Check if is present
  stat:
    path: /usr/bin/libreoffice
  register: libreoffice_exists

- name: Libre Office | Ensure that exists a version in this release
  uri:
    url: "http://ppa.launchpad.net/libreoffice/ppa/ubuntu/dists/{{ ansible_distribution_release }}/"
    method: HEAD
  ignore_errors: yes
  retries: 3
  register: libreoffice_repository_release_exists

- name: Libre Office  | Check if repository is configured
  stat:
    path: /etc/apt/sources.list.d/libreoffice.list
  register: libreoffice_repository_exists

- name: Libre Office | Add package repository
  apt_repository:
    repo: "ppa:libreoffice/ppa"
    filename: libreoffice
    update_cache: yes
    state: present
  become: true
  retries: 3
  when: libreoffice_repository_release_exists == True and libreoffice_repository_exists == false
  
- name: Libre Office | Install the package
  package:
    name:
      - libreoffice
      - libreoffice-l10n-pt-br
      - libreoffice-style-sifr
    state: present
    force_apt_get: true
  become: true
  retries: 3
  when: libreoffice_exists.stat.exists == false