---
- name: Microk8s | Install the snap
  snap:
    name: microk8s
    state: present
    classic: true
  retries: 3
  become: true

- name: Microk8 | Disable startup
  shell: snap disable microk8s
  become: true
  ignore_errors: true

- name: Microk8 | Add current user to microk8s group
  user: 
    name: "{{ ansible_user_id }}"
    groups: microk8s
    append: yes
  become: true