---
- name: MPV | Check if is present
  stat:
    path: /usr/bin/mpv
  register: mpv_bin_path

- name: MPV | Ensure that exists a version in this release
  uri:
    url: "http://ppa.launchpad.net/savoury1/mpv/ubuntu/dists/{{ ansible_distribution_release }}/"
    method: HEAD
  retries: 3
  ignore_errors: yes
  register: mpv_repo

- name: MPV | Add package repository
  apt_repository:
    repo: "ppa:savoury1/mpv"
    filename: mpv
    update_cache: yes
    state: present
  retries: 3
  become: true
  when: mpv_repo.status == 200

- name: MPV | Install the package
  package:
    name: mpv
    state: present
    force_apt_get: true
  retries: 3
  become: true
  when: mpv_bin_path.stat.exists == false