---
- name: Peek | Check if is present
  stat:
    path: /usr/bin/peek
  register: peek_bin_path

- name: Peek | Ensure that exists a version in this release
  uri:
    url: "http://ppa.launchpad.net/peek-developers/stable/ubuntu/dists/{{ ansible_distribution_release }}/"
    method: HEAD
  ignore_errors: yes
  retries: 3
  register: peek_repo

- name: Peek | Add package repository
  when: peek_repo.status == 200
  apt_repository:
    repo: "ppa:peek-developers/stable"
    filename: peek
    update_cache: yes
    state: present
  become: true
  retries: 3

- name: Peek | Install the package
  when: peek_bin_path.stat.exists == false and peek_repo.status == 200
  package:
    name: peek
    state: present
    force_apt_get: true
  become: true
  retries: 3
