---
- name: Plank | Ensure that exists a version in this release
  uri:
    url: "http://ppa.launchpad.net/ricotz/docky/ubuntu/dists/{{ ansible_distribution_release }}/"
    method: HEAD
  ignore_errors: yes
  retries: 3
  register: plank_repository_release_exists

- name: Plank | Check if repository is configured
  stat:
    path: /etc/apt/sources.list.d/plank.list
  register: plank_repository_exists

- name: Plank | Add package repository
  apt_repository:
    repo: "ricotz/docky"
    filename: plank
    update_cache: yes
    state: present
  become: true
  retries: 3
  when: plank_repository_release_exists == True and plank_repository_exists == false
  
- name: Plank | Install the package
  package:
    name:
      - plank
    state: present
    force_apt_get: true
  retries: 3
  become: true

- name: Plank | Change file ownership, group and permissions
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory

- name: Plank | Check if Plank is present
  stat:
    path: "{{ ansible_env.HOME }}/.config/autostart/plank.desktop"
  register: plank_autostart_path

- name: Plank | Ensure that there is a autostart file
  template:
    src: application.desktop
    dest: "{{ ansible_env.HOME }}/.config/autostart/plank.desktop"
  vars:
    name: Plank
    description: Plank
    executable: plank
  when: plank_autostart_path.stat.exists == false