---
- name: Podman | Check if repository is configured
  stat:
    path: /etc/apt/sources.list.d/kubic-libcontainers.list
  register: podman_repository_file_path

- name: Podman | Check if the binary is present
  stat:
    path: "/usr/bin/podman"
  register: podman_bin_path

- name: Install the package
  when: podman_bin_path.stat.exists == false
  block:
    - name: Podman | Ensure that exists a version in this release
      uri:
        url: "https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ansible_distribution_version}}"
        method: HEAD
      ignore_errors: yes
      retries: 3
      register: podman_repository_release_exists

    - name: Podman | Add an Apt signing key
      apt_key:
        url: https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ansible_distribution_version}}/Release.key
        state: present
      retries: 3
      become: true
      when: podman_repository_release_exists.status == 200

    - name: Podman | Configure the repository
      apt_repository:
        repo: "deb https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_{{ansible_distribution_version}}/ /"
        state: present
        filename: kubic-libcontainers
        update_cache: true
      become: true
      retries: 3
      when: podman_repository_file_path.stat.exists == false and podman_repository_release_exists.status == 200

    - name: Podman | Install or Upgrade
      package:
        name: podman
        state: latest
        force_apt_get: yes
      become: true
      retries: 3
      when: podman_repository_release_exists.status == 200
