---
- name: Qbittorrent | Check if is present
  stat:
    path: /usr/bin/qbittorrent
  register: qbittorrent_bin_path

- name: Qbittorrent | Ensure that exists a version in this release
  uri:
    url: "http://ppa.launchpad.net/qbittorrent-team/qbittorrent-stable/ubuntu/dists/{{ ansible_distribution_release }}/"
    method: HEAD
  ignore_errors: yes
  retries: 3
  register: qbittorrent_repo

- name: Qbittorrent | Add package repository
  when: qbittorrent_repo.status == 200
  apt_repository:
    repo: "ppa:qbittorrent-team/qbittorrent-stable"
    filename: qbittorrent
    update_cache: yes
    state: present
  become: true
  retries: 3

- name: Qbittorrent | Install the package
  when: qbittorrent_bin_path.stat.exists == false
  package:
    name: qbittorrent
    state: present
    force_apt_get: true
  become: true
  retries: 3
