---
- name: SDKMAN | Check if is present
  stat:
    path: "{{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh"
  register: sdkman_bin_path

- name: SDKMAN | Download and Install
  when: sdkman_bin_path.stat.exists == false
  block:
    - name: SDKMAN | Download the binary
      get_url:
        url: https://get.sdkman.io
        dest: /tmp/sdkman.sh
        mode: 0777
        validate_certs: false
      retries: 3
    - name: SDKMAN | Execute the binary
      shell: "/tmp/sdkman.sh"

- name: SDKMAN | Check if Java 8 is present
  stat:
    path: "{{ ansible_env.HOME }}/.sdkman/candidates/java/8.0.265-open/bin/java"
  register: sdkman_java8_bin_path

- name: SDKMAN | Install Java 8
  when: sdkman_java8_bin_path.stat.exists == false
  shell: ". {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install java 8.0.265-open"
  args:
    executable: /bin/bash

- name: SDKMAN | Check if Java 14 is present
  stat:
    path: "{{ ansible_env.HOME }}/.sdkman/candidates/java/14.0.2-open/bin/java"
  register: sdkman_java14_bin_path

- name: SDKMAN | Install Java 14
  when: sdkman_java14_bin_path.stat.exists == false
  shell: ". {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install java 14.0.2-open"
  args:
    executable: /bin/bash
  retries: 3

- name: SDKMAN | Install Maven
  shell: ". {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install maven"
  args:
    executable: /bin/bash
  retries: 3
  ignore_errors: true

- name: SDKMAN | Install Groovy
  shell: ". {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install groovy"
  args:
    executable: /bin/bash
  retries: 3
  ignore_errors: true
