---
- name: SDKMAN | Check if is present
  stat:
    path: "{{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh"
  register: sdkman_bin_path

- name: SDKMAN | Download and Install
  block:
  - name: SDKMAN | Download the binary
    get_url:
      url: https://get.sdkman.io
      dest: /tmp/sdkman.sh
      mode: 0777
      validate_certs: false
  - name: SDKMAN | Execute the binary
    shell: "/tmp/sdkman.sh"
  when: sdkman_bin_path.stat.exists == false

- name: SDKMAN | Check if Java 8 is present
  stat:
    path: "{{ ansible_env.HOME }}/.sdkman/candidates/java/8.0.252.hs-adpt/bin/java"
  register: sdkman_java8_bin_path

- name: SDKMAN | Install Java 8
  shell: ". {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install java 8.0.252.hs-adpt"
  args:
    executable: /bin/bash
  when: sdkman_java8_bin_path.stat.exists == false

- name: SDKMAN | Check if Java 14 is present
  stat:
    path: "{{ ansible_env.HOME }}/.sdkman/candidates/java/14.0.1.hs-adpt/bin/java"
  register: sdkman_java14_bin_path

- name: SDKMAN | Install Java 14
  shell: ". {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install java 14.0.1.hs-adpt"
  args:
    executable: /bin/bash
  when: sdkman_java14_bin_path.stat.exists == false

- name: SDKMAN | Install Maven
  shell: ". {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install maven"
  args:
    executable: /bin/bash
  ignore_errors: true

- name: SDKMAN | Install Groovy
  shell: ". {{ ansible_env.HOME }}/.sdkman/bin/sdkman-init.sh && sdk install groovy"
  args:
    executable: /bin/bash
  ignore_errors: true
