---
- name: Check if Spacevim exists
  stat:
    path: "{{ ansible_env.HOME }}/.SpaceVim/"
  register: spacevim_exists

- name: SpaceVim | Install or Upgrade SpaceVim
  block:
  - name: SpaceVim | Ensure that vim package is installed
    package: 
      name:
        - neovim
        - git 
        - curl
        - global
      state: present 
      force_apt_get: yes
    become: true

  - name: SpaceVim | Download the installer
    get_url:
      url: https://spacevim.org/install.sh
      dest: /tmp/spacevim-installer.sh
      mode: '0555'
      validate_certs: false
  - name: SpaceVim | Execute the installer
    shell: bash /tmp/spacevim-installer.sh

  - name: SpaceVim | Remove the installer
    file:
      state: absent
      path: /tmp/spacevim-installer.sh

  - name: SpaceVim | Copy configuration file
    synchronize:
      src: "init.toml"
      dest: "{{ ansible_env.HOME }}/.SpaceVim.d/"
  when: spacevim_exists.stat.exists == false

- name: Spacevim | Layers | Ensure that the html dependency is present
  shell: ". {{ ansible_env.HOME }}/.nvm/nvm.sh && npm i -g vscode-html-languageserver-bin"

- name: Spacevim | Layers | Ensure that the markdown dependency is present
  shell: ". {{ ansible_env.HOME }}/.nvm/nvm.sh && npm i -g prettier"

- name: Spacevim | Layers | Ensure that the typescript dependency is present
  shell: ". {{ ansible_env.HOME }}/.nvm/nvm.sh && npm i -g typescript"

- name: Spacevim | Layers | Ensure that the python dependency is present
  pip:
    name:
      - flake8
      - yapf
      - autoflake
      - isort
      - coverage
    extra_args: --user
