- name: Check if Spotify is present
  stat:
    path: /usr/bin/spotify
  register: spotify_exists

- name: Sound Switcher | Check if repository is configured
  stat:
    path: /etc/apt/sources.list.d/spotify.list
  register: spotify_repo_file

- name: Spotify | Install Spotify
  when: spotify_repo_file.stat.exists == false and spotify_exists.stat.exists == false
  block:
    - name: Spotify | Add Spotify apt key
      apt_key:
        url: https://download.spotify.com/debian/pubkey_0D811D58.gpg
        state: present
      become: true
      retries: 3

    - name: Spotify | Add Spotify repository
      apt_repository:
        repo: "deb http://repository.spotify.com stable non-free"
        filename: spotify
        update_cache: yes
        state: present
      become: true
      retries: 3

    - name: Spotify | Install the package
      package:
        name: spotify-client
        state: present
        force_apt_get: true
      become: true
      retries: 3
