---
- name: Check if Sublime Text is present
  stat:
    path: /usr/bin/subl
  register: subl_exists

- name: Sublime Text | Install Sublime Text
  block:
  - name: Sublime Text | Add apt key
    apt_key:
      url: https://download.sublimetext.com/sublimehq-pub.gpg
      state: present
    become: true
  - name: Sublime Text | Add the repository
    apt_repository:
      repo: "deb https://download.sublimetext.com/ apt/stable/"
      filename: sublimetext
      update_cache: yes
      state: present
    become: true
  - name: Sublime Text | Install the package
    package:
      name: sublime-text
      state: present
      force_apt_get: true
    become: true
  when: subl_exists.stat.exists == false