---
- name: Terminal | Install base16 colors
  git:
    repo: https://github.com/chriskempson/base16-shell
    dest: "{{ ansible_env.HOME }}/.config/base16-shell"
  retries: 3

- name: Terminal | Include related tasks
  include_tasks: "{{ terminal_tasks }}.yml"
  loop:
    - tmux
    - zsh
    - alacritty
  loop_control:
    loop_var: terminal_tasks

# - name: Terminal | Copy configurations file
#   copy:
#     src: terminalrc
#     dest: "{{ ansible_env.HOME }}/.config/xfce4/terminal"
#   ignore_errors: true
