---

- name: Check if Tmux is present
  stat:
    path: /usr/bin/tmux
  register: tmux_exists

- name: Tmux | Install and configure
  when: tmux_exists.stat.exists == false
  block:
    - name: Tmux | Install the package
      package:
        name:
          - tmux
          - fzf
        state: present
        force_apt_get: true
      become: true
      retries: 3

    - name: Tmux | Install TMP
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
      retries: 3


- name: Tmux | Install Tmux plugins dependencies
  package:
    name: xsel
    state: present
    force_apt_get: true
  retries: 3
  become: true

- name: Tmux | Copy configurations file
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"