---
- include_tasks: flatpak.yml

- name: Upgrade | Execute all apt related tasks
  block:
    - name: Upgrade | Update cache
      apt:
        update_cache: yes
        cache_valid_time: 600
        force_apt_get: yes
      become: true
      register: upgrade_cache
      retries: 3
      until: "'Failed' not in upgrade_cache"

    - name: Upgrade | Ensure that all packages are upgraded
      apt:
        upgrade: dist
        force_apt_get: yes
      register: apt_result
      become: true
      retries: 3

    - name: Upgrade | Autoremove unused packages
      apt:
        autoremove: yes
        force_apt_get: yes
      register: apt_result
      changed_when: "'packages will be REMOVED' in apt_result.stdout"
      become: true

- name: Upgrade | Check if flatpak exists
  stat:
    path: /usr/bin/flatpak
  register: flatpak_bin_path

- name: Upgrade | Upgrade Flatpak related packages
  when: flatpak_bin_path.stat.exists == True
  shell: flatpak update -y
  retries: 3

- name: Upgrade | Upgrade Snap related packages
  shell: snap refresh
  become: true
  retries: 3
