---
- name: Vagrant | Check if is installed
  stat:
    path: /usr/bin/vagrant
  register: vagrant_exists

- name: Podman | Ensure that exists a version in this release
  uri:
    url: "https://apt.releases.hashicorp.com/dists/{{ ansible_distribution_release }}/InRelease"
    method: HEAD
  ignore_errors: yes
  retries: 3
  register: vagrant_repository_release_exists

- name: Vagrant | Install the package
  when: vagrant_repository_release_exists.status == 200 and vagrant_exists.stat.exists == false
  block:
    - name: Vagrant | Add apt key
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg
        state: present
      retries: 3
      become: true
      
    - name: Vagrant | Add package repository
      apt_repository:
        repo: "deb [arch=amd64] https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"
        filename: vagrant
        update_cache: yes
        state: present
      become: true
      retries: 3

    - name: Vagrant | Install the package
      package:
        name: vagrant
        state: present
        force_apt_get: true
      retries: 3
      become: true
