---
- name: VSCode | Check if is present
  stat:
    path: /usr/bin/code
  register: vscode_exists

- name: VSCode | Install Visual Code
  when: vscode_exists.stat.exists == false
  block:
    - name: VSCode | Add Visual Code apt key
      apt_key:
        url: https://packages.microsoft.com/keys/microsoft.asc
        state: present
      become: true
      retries: 3

    - name: VSCode | Add Visual Code repository
      apt_repository:
        repo: "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"
        filename: vscode
        update_cache: yes
        state: present
      become: true
      retries: 3

    - name: VSCode | Install Visual Code
      package:
        name: code
        state: present
        force_apt_get: true
      become: true
      retries: 3
