---

- name:  ZSH | Check if the binary is present
  stat:
    path: /usr/bin/zsh
  register: zsh_exists

- name: ZSH | Install and configure
  when: zsh_exists.stat.exists == false
  block:
    - name: ZSH | Install the package
      package:
        name: zsh
        state: present
        force_apt_get: true
      become: true
      retries: 3

- name:  ZSH | Zplug | Check if the binary is present
  stat:
    path: "{{ ansible_env.HOME }}/.zplug/init.zsh"
  register: zplug_exists

- name: ZSH | Zplug | Download the installer
  get_url:
    url: https://raw.githubusercontent.com/zplug/installer/master/installer.zsh
    dest: /tmp/zplug-installer.sh
    mode: "0555"
    validate_certs: false
  retries: 3
  when: zplug_exists.stat.exists == false

- name: ZSH | Zplug | Execute the installer
  shell: zsh /tmp/zplug-installer.sh
  when: zplug_exists.stat.exists == false

- name: ZSH | Zplug | Remove the installer
  file:
    state: absent
    path: /tmp/lunarvim-installer.sh
  when: zplug_exists.stat.exists == false

- name: ZSH | Copy configurations file
  copy:
    src: zshrc
    dest: "{{ ansible_env.HOME }}/.zshrc"

- name: Terminal | ZSH | Change default shell to zsh
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
  become: true
