---
- name: Includes the all development tasks
  block:
    - name: Includes HashiCorp related tasks
      include_tasks: hashicorp.yml
    - name: Includes Cloud Vendor cli tasks
      include_tasks: cloud_provider_cli.yml
    - name: Includes Java tasks
      include_tasks: java.yml
    - name: Includes IDE tasks
      include_tasks: ide.yml