---
- name: Check if Brave is present
  stat:
    path: /usr/bin/brave-browser
  register: brave_exists

- name: Brave | Ensure that exists a version in this release
  uri:
    url: "https://brave-browser-apt-release.s3.brave.com/dists/{{ ansible_distribution_release }}/InRelease"
  ignore_errors: yes
  register: brave_repository_release_exists
- name: Brave | Install the package
  block:
    - name: Brave | Add the key for apt
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        state: present
      become: true
    - name: Brave | add package repository
      apt_repository:
        repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
        filename: brave-browser
      become: true
    - name: Brave | Install the package
      package:
        name: brave-browser
        state: present
        force_apt_get: true
      become: true
  when: brave_exists.stat.exists == False and brave_repository_release_exists.status == 200

