---
- name: Browser | Include related tasks
  include_tasks: "{{ container_tasks }}.yml"
  loop:
    - firefox
    - googlechrome
    - vivaldi
    - opera
    - brave
  loop_control:
    loop_var: container_tasks