---

- name: Check if Firefox is present
  stat:
    path: /usr/bin/firefox
  register: firefox_exists

- name: Firefox | Install Firefox
  package:
    name: firefox
    state: preset
  when: firefox_exists.stat.exists == False
  
- name: Check if Google Chrome is present
  stat:
    path: /usr/bin/google-chrome
  register: google_chrome_exists

- name: Google Chrome | Install Google Chrome
  block:
  - name: Google Chrome | Add apt key
    apt_key:
      url: https://dl-ssl.google.com/linux/linux_signing_key.pub
      state: present
    become: yes
  - name: Google Chrome | Add package repository
    apt_repository:
      repo: "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main"
      filename: google-chrome
      update_cache: yes
      state: present
    become: yes
  - name: Google Chrome | Install the package
    package:
      name: google-chrome-stable
      state: present
      force_apt_get: true
    become: yes
  when: google_chrome_exists.stat.exists == False
  
- name: Check if Vivaldi is present
  stat:
    path: /usr/bin/vivaldi
  register: vivaldi_exists
- name: Vivaldi | Install the package
  block:
    - name: Vivaldi | Add the key for apt
      apt_key:
        url: https://repo.vivaldi.com/archive/linux_signing_key.pub
        state: present
      become: yes
    - name: Vivaldi | add package repository
      apt_repository:
        repo: "deb https://repo.vivaldi.com/archive/deb/ stable main"
        state: present
        update_cache: yes
      become: yes
    - name: Vivaldi | Install the package
      package:
        name: vivaldi-stable
        state: present
        force_apt_get: true
      become: yes
  when: vivaldi_exists.stat.exists == False


- name: Check if Opera is present
  stat:
    path: /usr/bin/opera
  register: opera_exists

- name: Opera | Install the package
  block:
    - name: Opera | Add the key for apt
      apt_key:
        url: http://deb.opera.com/archive.key
        state: present
      become: yes
    - name: Opera | add package repository
      apt_repository:
        repo: "deb https://deb.opera.com/opera-stable/ stable non-free"
        state: present
        update_cache: yes
        filename: opera-stable
      become: yes
    - name: Opera | Install the package
      package:
        name: opera-stable
        state: present
        force_apt_get: true
      become: yes
  when: opera_exists.stat.exists == False

- name: Check if Brave is present
  stat:
    path: /usr/bin/brave-browser
  register: brave_exists

- name: Brave | Install the package
  block:
    - name: Brave | Add the key for apt
      apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        state: present
      become: yes
    - name: Brave | add package repository
      apt_repository:
        repo: "deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ {{ ansible_distribution_release }} main"
        state: present
        update_cache: yes
        filename: brave-browser
      become: yes
    - name: Brave | Install the package
      package:
        name: brave-browser
        state: present
        force_apt_get: true
      become: yes
  when: brave_exists.stat.exists == False

