---
- name: AWS CLI | Check if AWS Cli is present
  stat:
    path: "{{ ansible_env.HOME }}/.local/bin/aws"
  register: awscli_exists
- name: AWS CLI | Install or Upgrade AWS cli
  block:
  - name: AWS CLI | Install or Upgrade AWS cli
    pip:
      name: awscli
      state: latest
  when: awscli_exists.stat.exists == False

- name: Azure CLI | Ensure that exists a version in this release
  uri:
    url: "https://packages.microsoft.com/repos/azure-cli/dists/{{ ansible_distribution_release }}/"
  ignore_errors: yes
  register: azurecli_repository_release_exists
- name: Azure CLI | Check if Azure Cli is present
  stat:
    path: "/usr/bin/az"
  register: azurecli_exists
- name: Azure CLI | Install or Upgrade Azure cli
  block:
  - name: Azure CLI | Ensures that the dependencies for Azure cli is installed
    package:
      name: "{{ azure_depedency }}"
      state: latest
      force_apt_get: yes
    become: yes
    with_list:
      - ca-certificates
      - curl
      - apt-transport-https
      - lsb-release
      - gnupg
    loop_control:
      loop_var: azure_depedency
  - name: Azure CLI | Add an Apt signing key for Azure cli
    apt_key:
      url: https://packages.microsoft.com/keys/microsoft.asc
      state: present
    become: yes
  - name: Azure CLI | Configure Azure cli repository
    apt_repository:
      repo: "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ {{ ansible_distribution_release }} main"
      state: present
      filename: azurecli
      update_cache: true
    become: yes
  - name: Azure CLI | Install or Upgrade Azure cli
    package:
      name: azure-cli
      state: latest
      force_apt_get: yes
    become: yes
  when: azurecli_exists.stat.exists == False and azurecli_repository_release_exists.status == 200


- name: Google Cloud CLI | Ensure that exists a version in this release
  uri:
    url: "https://packages.microsoft.com/repos/azure-cli/dists/{{ ansible_distribution_release }}/"
  ignore_errors: yes
  register: gcloud_repository_release_exists
- name: Google Cloud CLI | Check if Google Cloud CLI is present
  stat:
    path: "/usr/bin/gcloud"
  register: gcloud_exists
- name: Google Cloud CLI | Install or Upgrade Azure CLI
  block:
    - name: Google Cloud CLI | Add an Apt signing key for Google Cloud 
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      become: yes
    - name: Google Cloud CLI | Configure Google Cloud repository
      apt_repository:
        repo: "deb http://packages.cloud.google.com/apt cloud-sdk-{{ ansible_distribution_release }} main"
        state: present
        filename: gcloudcli
        update_cache: true
      become: yes
    - name: Google Cloud CLI | Install or Upgrade Google Cloud CLI
      package:
        name: google-cloud-sdk
        state: latest
        force_apt_get: yes
      become: yes
  when: gcloud_exists.stat.exists == False and gcloud_repository_release_exists.status == 200