---
- name: Container | Include related tasks
  include_tasks: "{{ container_tasks }}.yml"
  loop:
    - docker
    - dive
    - microk8s
    - docker-compose
    - kubectl
  loop_control:
    loop_var: container_tasks