---
- name: Docker | Check if is present
  stat:
    path: /usr/bin/docker
  register: docker_exists

- name: Docker | Install or Upgrade
  block:
  - name: Docker | Add apt key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
    become: yes
  - name: Docker | Add package repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
      filename: docker
      update_cache: yes
      state: present
    become: yes
  - name: Docker | Install the package
    package:
      name: docker-ce
      state: present
      force_apt_get: true
    become: yes
  when: docker_exists.stat.exists == False 


- name: Dive | Check if is present
  stat:
    path: /usr/local/bin/dive
  register: dive_exists

- name: Dive | Install or Upgrade
  block:
    - name: Dive | Recover all releases
      uri:
        url: https://api.github.com/repos/wagoodman/dive/releases
        return_content: true
        body_format: json
      register: dive_releases_response
    - name: Dive | Get deb url from latest version
      set_fact:
        dive_deb_download_url: "{{ dive_releases_response.content | from_json | first | json_query('assets[?content_type==`application/vnd.debian.binary-package`].browser_download_url') | first }}"
    - name: Dive | Install deb file
      apt:
        deb: "{{ dive_deb_download_url }}"
      become: yes
  when: dive_exists.stat.exists == False 