---
- name: Ensure that the repository is present
  apt_repository:
    repo: ppa:alexlarsson/flatpak
    state: present
    update_cache: yes
  become: yes
- name: Ensures that the package flatpak is installed
  package:
    name: "{{ item }}"
    state: present
    force_apt_get: yes
  become: yes
  with_list:
    - flatpak
    - gnome-software-plugin-flatpak
