---
- name: Check if Libre Office is present
  stat:
    path: /usr/bin/libreoffice
  register: libreoffice_exists

- name: Libre Office | Install Libre Office
  block:
  - name: Libre Office | Add package repository
    apt_repository:
      repo: "ppa:libreoffice/ppa"
      filename: libreoffice
      update_cache: yes
      state: present
    become: yes
  - name: Libre Office | Install the package
    package:
      name: "{{ libreoffice_dependency }}"
      state: present
      force_apt_get: true
    become: yes
    loop:
      - libreoffice
      - libreoffice-l10n-pt-br
      - libreoffice-style-sifr
    loop_control:
      loop_var: libreoffice_dependency
  when: libreoffice_exists.stat.exists == False