---
- name: Plank | Check if Plank is present
  stat:
    path: /usr/bin/plank
  register: plank_exists

- name: Plank | Install Plank
  block:
  - name: Plank | Add the repository
    apt_repository:
      repo: "ppa:ricotz/docky"
      filename: plank
      update_cache: yes
      state: present
    become: true
  - name: Plank | Install the package
    package:
      name: plank
      state: present
      force_apt_get: true
    become: true
  when: plank_exists.stat.exists == false

- name: Plank | Change file ownership, group and permissions
  file:
    path: "{{ ansible_env.HOME }}/.config/autostart"
    state: directory

- name: Plank | Check if Plank is present
  stat:
    path: "{{ ansible_env.HOME }}/.config/autostart/plank.desktop"
  register: plank_autostart_path

- name: Plank | Ensure that there is a autostart file
  template:
    src: application.desktop
    dest: "{{ ansible_env.HOME }}/.config/autostart/plank.desktop"
  vars:
    name: Plank
    description: Plank
    executable: plank
  when: plank_autostart_path.stat.exists == false