---
- name: Check if Spacevim exists
  stat:
    path: "{{ ansible_env.HOME }}/.SpaceVim/"
  register: spacevim_exists

- name: SpaceVim | Install or Upgrade SpaceVim
  block:
  - name: SpaceVim | Ensure that vim package is installed
    package: 
      name: "{{ spacevim_dependency }}"
      state: present 
      force_apt_get: yes
    loop:
      - vim
      - git 
      - curl
    loop_control:
      loop_var: spacevim_dependency
    become: true
  - name: SpaceVim | Download the installer
    get_url:
      url: https://spacevim.org/install.sh
      dest: /tmp/spacevim-installer.sh
      mode: '0555'
  - name: SpaceVim | Execute the installer
    shell: bash /tmp/spacevim-installer.sh
    become: no
  - name: SpaceVim | Remove the installer
    file:
      state: absent
      path: /tmp/spacevim-installer.sh
  - name: SpaceVim | Copy configuration file
    synchronize:
      src: "init.toml"
      dest: "{{ ansible_env.HOME }}/.SpaceVim.d/"
  when: spacevim_exists.stat.exists == False