---
- name: SpaceVim | Install or Upgrade SpaceVim
  block:
  - name: SpaceVim | Ensure that vim package is installed
    package: 
      name: "{{ item }}"
      state: present 
      force_apt_get: yes
    loop:
      - vim
      - git 
      - curl
    become: yes
  - name: SpaceVim | Download the installer
    get_url:
      url: https://spacevim.org/install.sh
      dest: /tmp/spacevim-installer.sh
      mode: '0555'
  - name: SpaceVim | Execute the installer
    shell: bash /tmp/spacevim-installer.sh
    become: no
  - name: SpaceVim | Remove the installer
    file:
      state: absent
      path: /tmp/spacevim-installer.sh