---
- name: Terminal | Install base16 colors
  git:
    repo: https://github.com/chriskempson/base16-shell
    dest: "{{ ansible_env.HOME }}/.config/base16-shell"

- name: Includes the all terminal tasks
  include_tasks: "{{ terminal_tasks }}.yml"
  loop:
    - tmux
    - zsh
  loop_control:
    loop_var: terminal_tasks

