---

- name: Check if Tmux is present
  stat:
    path: /usr/bin/tmux
  register: tmux_exists

- name: Tmux | Install and configure
  block:

    - name: Tmux | Install the package
      package:
        name: "{{ tmux_dependency }}"
        state: present
        force_apt_get: true
      loop:
        - tmux
        - fzf
      loop_control:
        loop_var: tmux_dependency
      become: true

    - name: Tmux | Install TMP
      git:
        repo: https://github.com/tmux-plugins/tpm
        dest: "{{ ansible_env.HOME }}/.tmux/plugins/tpm"
  when: tmux_exists.stat.exists == false

- name: Tmux | Copy configurations file
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"