---
- name: Tools | Include related tasks
  include_tasks: "{{ tools_tasks }}.yml"
  loop:
    - telegram
    - apachedirectory
    - whatsdesk
    - exa
    - bat
    - synapse
    - ulauncher
    - wireshark
    - whatsdesk
    - spacevim
    - virtualbox
  loop_control:
    loop_var: tools_tasks