---
- name: Tools | Include related tasks
  include_tasks: "{{ tools_tasks }}.yml"
  loop:
    - compiz
    - guake
    - telegram
    - apachedirectory
    - whatsdesk
    - exa
    - fd
    - bat
    - jq
    - skim
    - dust
    - synapse
    - ulauncher
    - wireshark
    - whatsdesk
    - virtualbox
    - discord
    - etcher
    - indicator
    - obsstudio
    - papirus
    - peek
    - plank
    - qbittorrent
    - skype
    - soundswitcher
    - whisker
    - xubuntudev
  loop_control:
    loop_var: tools_tasks