---
- name: Apache Directory | Check if there is a previous installation
  stat:
    path: /opt/ApacheDirectoryStudio/
  register: apachedirectory_installation_dir
- name: Install or Upgrade Apache Directory Studio
  block:
    - name: Apache Directory | Create temporary directory
      tempfile:
        state: directory
      register: apachedirectory_directory
    - name: Apache Directory | Get download page
      uri:
        url: https://directory.apache.org/studio/download/download-linux.html
        return_content: yes
      register: apachedirectory_download_page
    - name: Apache Directory | Set archive download link
      set_fact: 
        apachedirectory_archive_url: "{{ apachedirectory_download_page.content | regex_findall('(https?:\/\/.*linux.gtk.x86_64.tar.gz)') | first }}"
    - name: Apache Directory | Get archive
      get_url:
        url: "{{ apachedirectory_archive_url }}"
        dest: "{{ apachedirectory_directory.path }}/apachestudio.tar.gz"
      async: 1000
      poll: 0
      register: apachestudio_download_action
    - name: Apache Directory | Wait for download to end
      async_status:
        jid: '{{ apachestudio_download_action.ansible_job_id }}'
      register: apachestudio_job_result
      until: apachestudio_job_result.finished
      retries: 30
    - name: Apache Directory | Unarchive file
      unarchive:
        src: "{{ apachedirectory_directory.path }}/apachestudio.tar.gz"
        dest: "{{ apachedirectory_directory.path }}"
    - name: Apache Directory | Ensure that package directory is in /opt directory
      synchronize:
        src: "{{ apachedirectory_directory.path }}/ApacheDirectoryStudio"
        dest: /opt/
      become: yes
    - name: Apache Directory | Ensure that there is a directory to store shortcuts
      file:
        path: ~/.local/share/applications/
        state: directory
    - name: Apache Directory | Ensure that there is a shortcut to binary
      template:
        src: application.desktop
        dest: ~/.local/share/applications/apache-directory.desktop
      vars:
        name: Apache Directory Studio
        description: Apache Directory Studio
        executable: /opt/ApacheDirectoryStudio/ApacheDirectoryStudio
        icon: /opt/ApacheDirectoryStudio/icon.xpm
  when: apachedirectory_installation_dir.stat.exists == False

- name: Check if Telegram is present
  stat:
    path: /opt/telegram/Telegram
  register: telegram_exists

- name: Telegram | Install the package
  block:
    - name: Telegram | Add package repository
      apt_repository:
        repo: "ppa:atareao/telegram"
        state: present
        update_cache: yes
        filename: telegram
      become: yes
    - name: Telegram | Install the package
      package:
        name: telegram
        state: present
        force_apt_get: true
      become:  yes
  when: telegram_exists.stat.exists == False

- name: Dive | Check if is present
  stat:
    path: /usr/local/bin/dive
  register: dive_exists

- name: Dive | Install or Upgrade
  block:
    - name: Dive | Recover all releases
      uri:
        url: https://api.github.com/repos/wagoodman/dive/releases
        return_content: true
        body_format: json
      register: dive_releases_response
    - name: Dive | Get deb url from latest version
      set_fact:
        dive_deb_download_url: "{{ dive_releases_response.content | from_json | first | json_query('assets[?content_type==`application/vnd.debian.binary-package`].browser_download_url') | first }}"
    - name: Dive | Install deb file
      apt:
        deb: "{{ dive_deb_download_url }}"
      become: yes
  when: dive_exists.stat.exists == False 

- name: Exa | Check if is present
  stat:
    path: /usr/local/bin/exa
  register: exa_exists

- name: Exa | Install or Upgrade
  block:
    - name: Exa | Recover all releases
      uri:
        url: https://api.github.com/repos/ogham/exa/releases
        return_content: true
        body_format: json
      register: exa_releases_response
    - name: Exa | Get deb url from latest version
      set_fact:
        exa_zip_download_url: "{{ exa_releases_response.content | from_json | first | json_query('assets[?content_type==`application/zip`].browser_download_url') | first }}"
    - unarchive:
        src: "{{ exa_zip_download_url }}"
        dest: /usr/local/bin
        remote_src: true
      become: yes

    - debug: var=exa_zip_download_url

  when: exa_exists.stat.exists == False  



