---
- name: Tools | Include related tasks
  include_tasks: "{{ tools_tasks }}.yml"
  loop:
    - compiz
    - guake
    - telegram
    - apachedirectory
    - whatsdesk
    - exa
    - bat
    - synapse
    - ulauncher
    - wireshark
    - whatsdesk
    - spacevim
    - virtualbox
    - discord
    - etcher
    - indicator
    - obsstudio
    - papirus
    - peek
    - plank
    - qbittorrent
  loop_control:
    loop_var: tools_tasks