---
- name: Upgrade | Execute all apt related tasks
  block:
    - name: Upgrade | Update cache
      apt: 
        update_cache: yes
        cache_valid_time: 600
        force_apt_get: yes
      become: true
    - name: Upgrade | Ensure that all packages are upgraded
      apt: 
        upgrade: dist
        force_apt_get: yes
      register: apt_result
      become: true
    - name: Upgrade | Autoremove unused packages
      apt: 
        autoremove: yes
        force_apt_get: yes
      register: apt_result
      changed_when: "'packages will be REMOVED' in apt_result.stdout"
      become: true

- name: Upgrade | Check if flatpak exists
  stat:
    path: /usr/bin/flatpak
  register: flatpak_exists
  
- name: Upgrade | Upgrade Flatpak related packages
    shell: flatpak update -y
  when: flatpak_exists.stat.exists == True

- name: Upgrade | Upgrade Snap related packages
  shell: snap refresh
  become: true
